feat: Threads richtig anzeigen
top-22/forum pull request #15
Opened 2023-04-11 20:57 UTC by Rotwolf

- [ ] Anzeige der Threads
- - [ ] Threadname
- - [ ]

2023-04-12 16:28 UTC, joshuajeschek commented
wenn thread creator nicht in der datenbank erfasst wird, kannst du das gerne hinzufügen, da du es ja brauchst

2023-04-24 11:08 UTC, justinexner commented
Würde erstmal main in den Branch rebasen (wie letzte Woche erklärt in VSCode), bevor ich was reviewen würde ^^

2023-04-24 15:43 UTC, justinexner commented on src/pages/room/[roomId].tsx
> +                          <div className="ms-auto position-absolute top-0 end-0 p-2">
Vielleicht noch einen Button, draus machen?

2023-04-24 15:50 UTC, justinexner approved these changes
Approved

2023-04-25 13:07 UTC, joshuajeschek requested changes
größtenteils sind mir in getServerSideProps unnötige Aufrufe aufgefallen, aber wenn du da eine Erklärung hast bin ich ganz Ohr :)

2023-04-25 13:07 UTC, joshuajeschek commented on src/pages/room/[roomId].tsx
> +            <button className="btn btn-primary">CREATE POST</button>
```suggestion
            <Button>CREATE POST</Button>
```
Bitte zu Buttons von `react-bootstrap` wechseln (muss noch importiert werden)
- theoretisch kann man dann auch die `className` property weglassen, da `btn` von `react-bootstrap` hinzugefügt wird und `btn-primary` der default dort ist

2023-04-25 13:07 UTC, joshuajeschek commented on src/pages/room/[roomId].tsx
> +                          </button>
```suggestion
                          <Button className="btn-secondary ms-auto position-absolute top-0 end-0 p-2">
                            Optionen {/*Popup für Optionen hinzufügen */}
                          </Button>
```
s.o., hier hab ich einen `btn-secondary` drauß gemacht, da default bei `react-bootstrap` `btn-primary` ist

2023-04-27 14:28 UTC, Rotwolf commented
Ich gehe die Änderungen morgen in der Tiefe durch und versuche alles zu implementieren.

2023-04-28 13:56 UTC, Rotwolf commented on src/pages/room/[roomId].tsx
> -    .findFirst({ where: { id: roomId }, include: { users: true } })
Ich hatte das Probiert aber nicht hinbekommen ^^

2023-04-28 14:16 UTC, Rotwolf commented on src/pages/room/[roomId].tsx
> +      })),
ich musste das ganze noch ein wenig ändern, da ich sonst aus Room User natürlich nicht auf den Namen zugreifen kann.
Kannst du dir ja dann gleich nochmal anschauen.

2023-04-29 08:38 UTC, joshuajeschek commented on src/pages/room/[roomId].tsx
> +      })),
ah ja geht klar :)

2023-04-29 08:39 UTC, joshuajeschek approved these changes
is nice

2023-04-29 10:53 UTC, merged