[feat] Popup functionality added to CreatePost
top-22/forum pull request #17
Opened 2023-04-13 17:17 UTC by sar-sturm

2023-04-17 10:30 UTC, joshuajeschek commented
Kannst du bitte noch dafür sorgen dass der build durchgeht?

2023-04-17 11:46 UTC, sar-sturm commented on src/components/createPostPopup/surveyPost.tsx
> +              id="title"
Meinst du bzgl. title in SurveyPost und TextPost? Tbh kein Plan, alles hat funktioniert und ich hab nicht weiter drueber nachgedacht. Wenn das nicht passt, muesste ich mir das spaeter noch anschauen

2023-04-17 11:53 UTC, sar-sturm commented
> 
billo loesung aber was besseres schaffe im moment nicht mehr

2023-04-28 08:42 UTC, sar-sturm commented
![image](https://user-images.githubusercontent.com/83303430/235099741-5da9e3db-c051-4bb7-b081-3e290bc8ba39.png)
so siehts aktuell aus. Passt das so?

2023-04-30 11:29 UTC, joshuajeschek requested changes
nur paar kleinigkeiten, den großteil hab ich ja so oder so schon angefasst :)

2023-04-30 11:29 UTC, joshuajeschek commented on src/components/createPostPopup/index.tsx
> +              </button>
```suggestion
              <Button
                className="m-1"
                type="button"
                onClick={openTextPost}
              >
                Text Post
              </Button>
              <Button
                className="m-1"
                type="button"
                onClick={openSurveyPost}
              >
                Survey Post
              </Button>
```
Umwandlung zu `react-bootstrap`

2023-04-30 11:29 UTC, joshuajeschek commented on src/components/createPostPopup/surveyPost.tsx
>          <br></br>
☹️

2023-04-30 11:29 UTC, joshuajeschek commented on src/components/createPostPopup/surveyPost.tsx
> +
```suggestion

```

2023-04-30 11:29 UTC, joshuajeschek commented on src/components/createPostPopup/surveyPost.tsx
> +          font-size: 23px;
absolute größten (`px`) sind sehr schlecht
der bootstrappigere weg wäre das so oder so oben zu setzen, die textgröße, in `className`:
https://getbootstrap.com/docs/5.3/utilities/text/#font-size

2023-04-30 11:29 UTC, joshuajeschek commented on src/components/createPostPopup/surveyPost.tsx
> +          color: white;
auch hier, das kann man alles mit bootstrap in den `className`s machen, und da passiert auch nix unerwartetes wenn man später mal ein `div` hinzufügt

2023-04-30 11:29 UTC, joshuajeschek commented on src/components/createPostPopup/textPost.tsx
>        `}</style>
siehe letzter kommentar

2023-05-01 18:25 UTC, sar-sturm commented on src/components/createPostPopup/surveyPost.tsx
> +
oops übersehen

2023-05-02 08:48 UTC, joshuajeschek approved these changes
ok

2023-05-02 08:52 UTC, merged